#hasheq((name . "syncpilot")
        (display-name . "SyncPilot")
        (version . "0.7.0")
        (build . 4)
        (identifier . "site.jrtx.syncpilot")
        (release-channel . stable)
        (url-schemes . ())
        (file-associations . ())
        (macos-min-version . "14.0")
        (windows-min-version . "10.0.19041.0")
        (backend . "app/backend.rkt")
        (module . "backend")
        (entry . "start")
        (protocol . 1)
        (linux-icon . "assets/icon-512.png")
        (linux-formats . ("deb" "appimage")))
