// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig {
    public static let moduleName = "backend"
    public static let entryName = "start"
    public static let displayName = "SyncPilot"
    public static let version = "0.4.0"
    public static let build: Int64 = 1
    public static let identifier = "site.jrtx.syncpilot"
    public static let releaseChannel = "stable"
}

public enum DaemonPhase: String, Sendable {
    case stopped = "stopped"
    case starting = "starting"
    case running = "running"
    case crashed = "crashed"
    case failed = "failed"
}

public enum PortProbe: String, Sendable {
    case compatible = "compatible"
    case foreign = "foreign"
    case unreachable = "unreachable"
}

public struct DaemonStatus: Sendable {
    public let phase: DaemonPhase
    public let pid: Int64?
    public let uptime_secs: Int64?
    public let binary: String?
    public let error: String?
    public let autostart: Bool
    public init(phase: DaemonPhase, pid: Int64?, uptime_secs: Int64?, binary: String?, error: String?, autostart: Bool) {
        self.phase = phase
        self.pid = pid
        self.uptime_secs = uptime_secs
        self.binary = binary
        self.error = error
        self.autostart = autostart
    }
}

public struct Handoff: Sendable {
    public let proxy_url: String
    public let daemon_version: String?
    public let phase: DaemonPhase
    public init(proxy_url: String, daemon_version: String?, phase: DaemonPhase) {
        self.proxy_url = proxy_url
        self.daemon_version = daemon_version
        self.phase = phase
    }
}

public struct InstallResult: Sendable {
    public let ok: Bool
    public let path: String?
    public let error: String?
    public init(ok: Bool, path: String?, error: String?) {
        self.ok = ok
        self.path = path
        self.error = error
    }
}

public struct Settings: Sendable {
    public let rslsync_path: String
    public let webui_port: Int64
    public let webui_login: String
    public let has_password: Bool
    public let device_name: String
    public let autostart: Bool
    public let restart_on_crash: Bool
    public let keep_daemon_on_exit: Bool
    public let close_to_tray: Bool
    public let settings_version: Int64
    public init(rslsync_path: String, webui_port: Int64, webui_login: String, has_password: Bool, device_name: String, autostart: Bool, restart_on_crash: Bool, keep_daemon_on_exit: Bool, close_to_tray: Bool, settings_version: Int64) {
        self.rslsync_path = rslsync_path
        self.webui_port = webui_port
        self.webui_login = webui_login
        self.has_password = has_password
        self.device_name = device_name
        self.autostart = autostart
        self.restart_on_crash = restart_on_crash
        self.keep_daemon_on_exit = keep_daemon_on_exit
        self.close_to_tray = close_to_tray
        self.settings_version = settings_version
    }
}

public struct SettingsDraft: Sendable {
    public let rslsync_path: String
    public let webui_port: Int64
    public let webui_login: String
    public let device_name: String
    public let autostart: Bool
    public let restart_on_crash: Bool
    public let keep_daemon_on_exit: Bool
    public let close_to_tray: Bool
    public init(rslsync_path: String, webui_port: Int64, webui_login: String, device_name: String, autostart: Bool, restart_on_crash: Bool, keep_daemon_on_exit: Bool, close_to_tray: Bool) {
        self.rslsync_path = rslsync_path
        self.webui_port = webui_port
        self.webui_login = webui_login
        self.device_name = device_name
        self.autostart = autostart
        self.restart_on_crash = restart_on_crash
        self.keep_daemon_on_exit = keep_daemon_on_exit
        self.close_to_tray = close_to_tray
    }
}

public struct Speeds: Sendable {
    public let down_bytes: Int64
    public let up_bytes: Int64
    public init(down_bytes: Int64, up_bytes: Int64) {
        self.down_bytes = down_bytes
        self.up_bytes = up_bytes
    }
}

public struct TrialResult: Sendable {
    public let ok: Bool
    public let error: String?
    public init(ok: Bool, error: String?) {
        self.ok = ok
        self.error = error
    }
}

private func encode_DaemonPhase(_ v: DaemonPhase) -> RivetValue { .string(v.rawValue) }
private func encode_Int64(_ v: Int64) -> RivetValue { .int64(v) }
private func encode__Optional_Int64_(_ v: Int64?) -> RivetValue { v.map(encode_Int64) ?? .null }
private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode__Optional_String_(_ v: String?) -> RivetValue { v.map(encode_String) ?? .null }
private func encode_Bool(_ v: Bool) -> RivetValue { .bool(v) }
private func encode_DaemonStatus(_ v: DaemonStatus) -> RivetValue { .list([encode_DaemonPhase(v.phase), encode__Optional_Int64_(v.pid), encode__Optional_Int64_(v.uptime_secs), encode__Optional_String_(v.binary), encode__Optional_String_(v.error), encode_Bool(v.autostart)]) }
private func encode_Handoff(_ v: Handoff) -> RivetValue { .list([encode_String(v.proxy_url), encode__Optional_String_(v.daemon_version), encode_DaemonPhase(v.phase)]) }
private func encode_Settings(_ v: Settings) -> RivetValue { .list([encode_String(v.rslsync_path), encode_Int64(v.webui_port), encode_String(v.webui_login), encode_Bool(v.has_password), encode_String(v.device_name), encode_Bool(v.autostart), encode_Bool(v.restart_on_crash), encode_Bool(v.keep_daemon_on_exit), encode_Bool(v.close_to_tray), encode_Int64(v.settings_version)]) }
private func encode_Speeds(_ v: Speeds) -> RivetValue { .list([encode_Int64(v.down_bytes), encode_Int64(v.up_bytes)]) }
private func encode_Void(_ v: Void) -> RivetValue { .null }
private func encode_InstallResult(_ v: InstallResult) -> RivetValue { .list([encode_Bool(v.ok), encode__Optional_String_(v.path), encode__Optional_String_(v.error)]) }
private func encode_TrialResult(_ v: TrialResult) -> RivetValue { .list([encode_Bool(v.ok), encode__Optional_String_(v.error)]) }
private func encode_PortProbe(_ v: PortProbe) -> RivetValue { .string(v.rawValue) }
private func encode_SettingsDraft(_ v: SettingsDraft) -> RivetValue { .list([encode_String(v.rslsync_path), encode_Int64(v.webui_port), encode_String(v.webui_login), encode_String(v.device_name), encode_Bool(v.autostart), encode_Bool(v.restart_on_crash), encode_Bool(v.keep_daemon_on_exit), encode_Bool(v.close_to_tray)]) }

private func decode_DaemonPhase(_ v: RivetValue) throws -> DaemonPhase { guard case .string(let x) = v, let result = DaemonPhase(rawValue: x) else { throw RivetGeneratedError.typeMismatch("DaemonPhase") }; return result }
private func decode_Int64(_ v: RivetValue) throws -> Int64 { guard case .int64(let x) = v else { throw RivetGeneratedError.typeMismatch("Int64") }; return x }
private func decode__Optional_Int64_(_ v: RivetValue) throws -> Int64? { if case .null = v { return nil }; return try decode_Int64(v) }
private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode__Optional_String_(_ v: RivetValue) throws -> String? { if case .null = v { return nil }; return try decode_String(v) }
private func decode_Bool(_ v: RivetValue) throws -> Bool { guard case .bool(let x) = v else { throw RivetGeneratedError.typeMismatch("Bool") }; return x }
private func decode_DaemonStatus(_ v: RivetValue) throws -> DaemonStatus { guard case .list(let xs) = v, xs.count == 6 else { throw RivetGeneratedError.typeMismatch("DaemonStatus") }; return DaemonStatus(phase: try decode_DaemonPhase(xs[0]), pid: try decode__Optional_Int64_(xs[1]), uptime_secs: try decode__Optional_Int64_(xs[2]), binary: try decode__Optional_String_(xs[3]), error: try decode__Optional_String_(xs[4]), autostart: try decode_Bool(xs[5])) }
private func decode_Handoff(_ v: RivetValue) throws -> Handoff { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("Handoff") }; return Handoff(proxy_url: try decode_String(xs[0]), daemon_version: try decode__Optional_String_(xs[1]), phase: try decode_DaemonPhase(xs[2])) }
private func decode_Settings(_ v: RivetValue) throws -> Settings { guard case .list(let xs) = v, xs.count == 10 else { throw RivetGeneratedError.typeMismatch("Settings") }; return Settings(rslsync_path: try decode_String(xs[0]), webui_port: try decode_Int64(xs[1]), webui_login: try decode_String(xs[2]), has_password: try decode_Bool(xs[3]), device_name: try decode_String(xs[4]), autostart: try decode_Bool(xs[5]), restart_on_crash: try decode_Bool(xs[6]), keep_daemon_on_exit: try decode_Bool(xs[7]), close_to_tray: try decode_Bool(xs[8]), settings_version: try decode_Int64(xs[9])) }
private func decode_Speeds(_ v: RivetValue) throws -> Speeds { guard case .list(let xs) = v, xs.count == 2 else { throw RivetGeneratedError.typeMismatch("Speeds") }; return Speeds(down_bytes: try decode_Int64(xs[0]), up_bytes: try decode_Int64(xs[1])) }
private func decode_Void(_ v: RivetValue) throws -> Void { guard case .null = v else { throw RivetGeneratedError.typeMismatch("Void") } }
private func decode_InstallResult(_ v: RivetValue) throws -> InstallResult { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("InstallResult") }; return InstallResult(ok: try decode_Bool(xs[0]), path: try decode__Optional_String_(xs[1]), error: try decode__Optional_String_(xs[2])) }
private func decode_TrialResult(_ v: RivetValue) throws -> TrialResult { guard case .list(let xs) = v, xs.count == 2 else { throw RivetGeneratedError.typeMismatch("TrialResult") }; return TrialResult(ok: try decode_Bool(xs[0]), error: try decode__Optional_String_(xs[1])) }
private func decode_PortProbe(_ v: RivetValue) throws -> PortProbe { guard case .string(let x) = v, let result = PortProbe(rawValue: x) else { throw RivetGeneratedError.typeMismatch("PortProbe") }; return result }
private func decode_SettingsDraft(_ v: RivetValue) throws -> SettingsDraft { guard case .list(let xs) = v, xs.count == 8 else { throw RivetGeneratedError.typeMismatch("SettingsDraft") }; return SettingsDraft(rslsync_path: try decode_String(xs[0]), webui_port: try decode_Int64(xs[1]), webui_login: try decode_String(xs[2]), device_name: try decode_String(xs[3]), autostart: try decode_Bool(xs[4]), restart_on_crash: try decode_Bool(xs[5]), keep_daemon_on_exit: try decode_Bool(xs[6]), close_to_tray: try decode_Bool(xs[7])) }

public enum RivetEvent: Sendable {
    case daemon_changed(DaemonStatus)

    public static func decode(name: String, value: RivetValue) throws -> RivetEvent {
        switch name {
        case "daemon-changed": return .daemon_changed(try decode_DaemonStatus(value))
        default: throw RivetGeneratedError.unknownEvent(name)
        }
    }
}

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func daemon_restart() async throws -> DaemonStatus {
        let result = try await client.call("daemon-restart", arguments: [])
        return try decode_DaemonStatus(result)
    }
    public func daemon_start() async throws -> DaemonStatus {
        let result = try await client.call("daemon-start", arguments: [])
        return try decode_DaemonStatus(result)
    }
    public func daemon_stop() async throws -> DaemonStatus {
        let result = try await client.call("daemon-stop", arguments: [])
        return try decode_DaemonStatus(result)
    }
    public func get_handoff() async throws -> Handoff {
        let result = try await client.call("get-handoff", arguments: [])
        return try decode_Handoff(result)
    }
    public func get_settings() async throws -> Settings {
        let result = try await client.call("get-settings", arguments: [])
        return try decode_Settings(result)
    }
    public func get_speeds() async throws -> Speeds {
        let result = try await client.call("get-speeds", arguments: [])
        return try decode_Speeds(result)
    }
    public func initialize() async throws -> Void {
        let result = try await client.call("initialize", arguments: [])
        return try decode_Void(result)
    }
    public func install_rslsync() async throws -> InstallResult {
        let result = try await client.call("install-rslsync", arguments: [])
        return try decode_InstallResult(result)
    }
    public func open_trial() async throws -> TrialResult {
        let result = try await client.call("open-trial", arguments: [])
        return try decode_TrialResult(result)
    }
    public func probe_port() async throws -> PortProbe {
        let result = try await client.call("probe-port", arguments: [])
        return try decode_PortProbe(result)
    }
    public func regenerate_password() async throws -> Settings {
        let result = try await client.call("regenerate-password", arguments: [])
        return try decode_Settings(result)
    }
    public func save_settings(draft: SettingsDraft) async throws -> Settings {
        let result = try await client.call("save-settings", arguments: [encode_SettingsDraft(draft)])
        return try decode_Settings(result)
    }

    // Shared state
    public func getStatus() async throws -> DaemonStatus {
        let result = try await client.getState("status")
        return try decode_DaemonStatus(result)
    }
    @discardableResult
    public func setStatus(_ value: DaemonStatus) async throws -> DaemonStatus {
        let result = try await client.setState("status", value: encode_DaemonStatus(value))
        return try decode_DaemonStatus(result)
    }
}
