// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "SyncPilot";
inline constexpr char kVersion[] = "0.6.1";
inline constexpr std::int64_t kBuild = 3;
inline constexpr char kIdentifier[] = "site.jrtx.syncpilot";
inline constexpr char kReleaseChannel[] = "stable";

enum class DaemonPhase { stopped, starting, running, crashed, failed };

enum class PortProbe { compatible, foreign, unreachable };

struct DaemonStatus {
  DaemonPhase phase;
  std::optional<std::int64_t> pid;
  std::optional<std::int64_t> uptime_secs;
  std::optional<std::string> binary;
  std::optional<std::string> error;
  bool autostart;
};

struct Handoff {
  std::string proxy_url;
  std::optional<std::string> daemon_version;
  DaemonPhase phase;
};

struct InstallResult {
  bool ok;
  std::optional<std::string> path;
  std::optional<std::string> error;
};

struct Settings {
  std::string rslsync_path;
  std::int64_t webui_port;
  std::string webui_login;
  bool has_password;
  std::string device_name;
  bool autostart;
  bool restart_on_crash;
  bool keep_daemon_on_exit;
  bool close_to_tray;
  std::string language;
  std::int64_t settings_version;
};

struct SettingsDraft {
  std::string rslsync_path;
  std::int64_t webui_port;
  std::string webui_login;
  std::string device_name;
  bool autostart;
  bool restart_on_crash;
  bool keep_daemon_on_exit;
  bool close_to_tray;
  std::string language;
};

struct Speeds {
  std::int64_t down_bytes;
  std::int64_t up_bytes;
};

struct TrialResult {
  bool ok;
  std::optional<std::string> error;
};

struct UpdateCheck {
  std::string status;
  std::optional<std::string> error;
  std::string current_version;
  std::optional<std::string> available_version;
  std::optional<std::int64_t> build;
  std::optional<std::string> published_at;
  std::optional<std::string> installer;
  std::optional<std::int64_t> size_bytes;
};

struct UpdateState {
  std::string phase;
  std::int64_t percent;
  std::optional<std::string> message;
  std::optional<std::string> downloaded_path;
  std::optional<std::string> available_version;
};

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode__Optional_String_(std::optional<std::string> const& v) { return v ? encode_String(*v) : rivet::Value{}; }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }
inline rivet::Value encode__Optional_Int64_(std::optional<std::int64_t> const& v) { return v ? encode_Int64(*v) : rivet::Value{}; }
inline rivet::Value encode_UpdateCheck(UpdateCheck const& v) { rivet::Value::List r; r.reserve(8); r.push_back(encode_String(v.status)); r.push_back(encode__Optional_String_(v.error)); r.push_back(encode_String(v.current_version)); r.push_back(encode__Optional_String_(v.available_version)); r.push_back(encode__Optional_Int64_(v.build)); r.push_back(encode__Optional_String_(v.published_at)); r.push_back(encode__Optional_String_(v.installer)); r.push_back(encode__Optional_Int64_(v.size_bytes)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_DaemonPhase(DaemonPhase v) { switch (v) { case DaemonPhase::stopped: return rivet::Value(std::string("stopped")); case DaemonPhase::starting: return rivet::Value(std::string("starting")); case DaemonPhase::running: return rivet::Value(std::string("running")); case DaemonPhase::crashed: return rivet::Value(std::string("crashed")); case DaemonPhase::failed: return rivet::Value(std::string("failed")); } throw std::runtime_error("invalid Rivet enum value"); }
inline rivet::Value encode_DaemonStatus(DaemonStatus const& v) { rivet::Value::List r; r.reserve(6); r.push_back(encode_DaemonPhase(v.phase)); r.push_back(encode__Optional_Int64_(v.pid)); r.push_back(encode__Optional_Int64_(v.uptime_secs)); r.push_back(encode__Optional_String_(v.binary)); r.push_back(encode__Optional_String_(v.error)); r.push_back(encode_Bool(v.autostart)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Handoff(Handoff const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_String(v.proxy_url)); r.push_back(encode__Optional_String_(v.daemon_version)); r.push_back(encode_DaemonPhase(v.phase)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Settings(Settings const& v) { rivet::Value::List r; r.reserve(11); r.push_back(encode_String(v.rslsync_path)); r.push_back(encode_Int64(v.webui_port)); r.push_back(encode_String(v.webui_login)); r.push_back(encode_Bool(v.has_password)); r.push_back(encode_String(v.device_name)); r.push_back(encode_Bool(v.autostart)); r.push_back(encode_Bool(v.restart_on_crash)); r.push_back(encode_Bool(v.keep_daemon_on_exit)); r.push_back(encode_Bool(v.close_to_tray)); r.push_back(encode_String(v.language)); r.push_back(encode_Int64(v.settings_version)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Speeds(Speeds const& v) { rivet::Value::List r; r.reserve(2); r.push_back(encode_Int64(v.down_bytes)); r.push_back(encode_Int64(v.up_bytes)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Void() { return rivet::Value{}; }
inline rivet::Value encode_InstallResult(InstallResult const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_Bool(v.ok)); r.push_back(encode__Optional_String_(v.path)); r.push_back(encode__Optional_String_(v.error)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_TrialResult(TrialResult const& v) { rivet::Value::List r; r.reserve(2); r.push_back(encode_Bool(v.ok)); r.push_back(encode__Optional_String_(v.error)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_PortProbe(PortProbe v) { switch (v) { case PortProbe::compatible: return rivet::Value(std::string("compatible")); case PortProbe::foreign: return rivet::Value(std::string("foreign")); case PortProbe::unreachable: return rivet::Value(std::string("unreachable")); } throw std::runtime_error("invalid Rivet enum value"); }
inline rivet::Value encode_SettingsDraft(SettingsDraft const& v) { rivet::Value::List r; r.reserve(9); r.push_back(encode_String(v.rslsync_path)); r.push_back(encode_Int64(v.webui_port)); r.push_back(encode_String(v.webui_login)); r.push_back(encode_String(v.device_name)); r.push_back(encode_Bool(v.autostart)); r.push_back(encode_Bool(v.restart_on_crash)); r.push_back(encode_Bool(v.keep_daemon_on_exit)); r.push_back(encode_Bool(v.close_to_tray)); r.push_back(encode_String(v.language)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_UpdateState(UpdateState const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_String(v.phase)); r.push_back(encode_Int64(v.percent)); r.push_back(encode__Optional_String_(v.message)); r.push_back(encode__Optional_String_(v.downloaded_path)); r.push_back(encode__Optional_String_(v.available_version)); return rivet::Value(std::move(r)); }

inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline std::optional<std::string> decode__Optional_String_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_String(v); }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
inline std::optional<std::int64_t> decode__Optional_Int64_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_Int64(v); }
inline UpdateCheck decode_UpdateCheck(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 8) throw std::runtime_error("Rivet result type mismatch: UpdateCheck"); return UpdateCheck{decode_String((*p)[0]), decode__Optional_String_((*p)[1]), decode_String((*p)[2]), decode__Optional_String_((*p)[3]), decode__Optional_Int64_((*p)[4]), decode__Optional_String_((*p)[5]), decode__Optional_String_((*p)[6]), decode__Optional_Int64_((*p)[7])}; }
inline DaemonPhase decode_DaemonPhase(rivet::Value const& v) { auto p = std::get_if<std::string>(&v.data); if (p) { if (*p == "stopped") return DaemonPhase::stopped; if (*p == "starting") return DaemonPhase::starting; if (*p == "running") return DaemonPhase::running; if (*p == "crashed") return DaemonPhase::crashed; if (*p == "failed") return DaemonPhase::failed; } throw std::runtime_error("Rivet result type mismatch: DaemonPhase"); }
inline DaemonStatus decode_DaemonStatus(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 6) throw std::runtime_error("Rivet result type mismatch: DaemonStatus"); return DaemonStatus{decode_DaemonPhase((*p)[0]), decode__Optional_Int64_((*p)[1]), decode__Optional_Int64_((*p)[2]), decode__Optional_String_((*p)[3]), decode__Optional_String_((*p)[4]), decode_Bool((*p)[5])}; }
inline Handoff decode_Handoff(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: Handoff"); return Handoff{decode_String((*p)[0]), decode__Optional_String_((*p)[1]), decode_DaemonPhase((*p)[2])}; }
inline Settings decode_Settings(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 11) throw std::runtime_error("Rivet result type mismatch: Settings"); return Settings{decode_String((*p)[0]), decode_Int64((*p)[1]), decode_String((*p)[2]), decode_Bool((*p)[3]), decode_String((*p)[4]), decode_Bool((*p)[5]), decode_Bool((*p)[6]), decode_Bool((*p)[7]), decode_Bool((*p)[8]), decode_String((*p)[9]), decode_Int64((*p)[10])}; }
inline Speeds decode_Speeds(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 2) throw std::runtime_error("Rivet result type mismatch: Speeds"); return Speeds{decode_Int64((*p)[0]), decode_Int64((*p)[1])}; }
inline void decode_Void(rivet::Value const& v) { if (!std::holds_alternative<std::monostate>(v.data)) throw std::runtime_error("Rivet result type mismatch: Void"); }
inline InstallResult decode_InstallResult(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: InstallResult"); return InstallResult{decode_Bool((*p)[0]), decode__Optional_String_((*p)[1]), decode__Optional_String_((*p)[2])}; }
inline TrialResult decode_TrialResult(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 2) throw std::runtime_error("Rivet result type mismatch: TrialResult"); return TrialResult{decode_Bool((*p)[0]), decode__Optional_String_((*p)[1])}; }
inline PortProbe decode_PortProbe(rivet::Value const& v) { auto p = std::get_if<std::string>(&v.data); if (p) { if (*p == "compatible") return PortProbe::compatible; if (*p == "foreign") return PortProbe::foreign; if (*p == "unreachable") return PortProbe::unreachable; } throw std::runtime_error("Rivet result type mismatch: PortProbe"); }
inline SettingsDraft decode_SettingsDraft(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 9) throw std::runtime_error("Rivet result type mismatch: SettingsDraft"); return SettingsDraft{decode_String((*p)[0]), decode_Int64((*p)[1]), decode_String((*p)[2]), decode_String((*p)[3]), decode_Bool((*p)[4]), decode_Bool((*p)[5]), decode_Bool((*p)[6]), decode_Bool((*p)[7]), decode_String((*p)[8])}; }
inline UpdateState decode_UpdateState(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: UpdateState"); return UpdateState{decode_String((*p)[0]), decode_Int64((*p)[1]), decode__Optional_String_((*p)[2]), decode__Optional_String_((*p)[3]), decode__Optional_String_((*p)[4])}; }
}  // namespace detail

struct Daemon_changedEvent { DaemonStatus value; };
using Event = std::variant<Daemon_changedEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "daemon-changed") return Event{Daemon_changedEvent{detail::decode_DaemonStatus(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::linux_runtime::Backend& backend) : backend_(backend) {}

  std::future<UpdateCheck> check_updates(bool force) { auto raw = backend_.call("check-updates", rivet::Value::List{detail::encode_Bool(force)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> UpdateCheck { return detail::decode_UpdateCheck(raw.get()); }); }
  [[nodiscard]] std::uint64_t check_updates_async(bool force, std::function<void(Result<UpdateCheck>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("check-updates", rivet::Value::List{detail::encode_Bool(force)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<UpdateCheck> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_UpdateCheck(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DaemonStatus> daemon_restart() { auto raw = backend_.call("daemon-restart", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DaemonStatus { return detail::decode_DaemonStatus(raw.get()); }); }
  [[nodiscard]] std::uint64_t daemon_restart_async(std::function<void(Result<DaemonStatus>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("daemon-restart", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<DaemonStatus> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DaemonStatus(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DaemonStatus> daemon_start() { auto raw = backend_.call("daemon-start", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DaemonStatus { return detail::decode_DaemonStatus(raw.get()); }); }
  [[nodiscard]] std::uint64_t daemon_start_async(std::function<void(Result<DaemonStatus>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("daemon-start", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<DaemonStatus> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DaemonStatus(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DaemonStatus> daemon_stop() { auto raw = backend_.call("daemon-stop", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DaemonStatus { return detail::decode_DaemonStatus(raw.get()); }); }
  [[nodiscard]] std::uint64_t daemon_stop_async(std::function<void(Result<DaemonStatus>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("daemon-stop", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<DaemonStatus> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DaemonStatus(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Handoff> get_handoff() { auto raw = backend_.call("get-handoff", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Handoff { return detail::decode_Handoff(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_handoff_async(std::function<void(Result<Handoff>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-handoff", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<Handoff> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Handoff(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Settings> get_settings() { auto raw = backend_.call("get-settings", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Settings { return detail::decode_Settings(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_settings_async(std::function<void(Result<Settings>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-settings", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<Settings> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Settings(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Speeds> get_speeds() { auto raw = backend_.call("get-speeds", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Speeds { return detail::decode_Speeds(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_speeds_async(std::function<void(Result<Speeds>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-speeds", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<Speeds> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Speeds(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> initialize() { auto raw = backend_.call("initialize", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t initialize_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("initialize", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<InstallResult> install_rslsync() { auto raw = backend_.call("install-rslsync", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> InstallResult { return detail::decode_InstallResult(raw.get()); }); }
  [[nodiscard]] std::uint64_t install_rslsync_async(std::function<void(Result<InstallResult>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("install-rslsync", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<InstallResult> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_InstallResult(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<TrialResult> open_trial() { auto raw = backend_.call("open-trial", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> TrialResult { return detail::decode_TrialResult(raw.get()); }); }
  [[nodiscard]] std::uint64_t open_trial_async(std::function<void(Result<TrialResult>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("open-trial", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<TrialResult> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_TrialResult(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<PortProbe> probe_port() { auto raw = backend_.call("probe-port", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> PortProbe { return detail::decode_PortProbe(raw.get()); }); }
  [[nodiscard]] std::uint64_t probe_port_async(std::function<void(Result<PortProbe>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("probe-port", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<PortProbe> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_PortProbe(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Settings> regenerate_password() { auto raw = backend_.call("regenerate-password", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Settings { return detail::decode_Settings(raw.get()); }); }
  [[nodiscard]] std::uint64_t regenerate_password_async(std::function<void(Result<Settings>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("regenerate-password", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<Settings> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Settings(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Settings> save_settings(SettingsDraft draft) { auto raw = backend_.call("save-settings", rivet::Value::List{detail::encode_SettingsDraft(draft)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Settings { return detail::decode_Settings(raw.get()); }); }
  [[nodiscard]] std::uint64_t save_settings_async(SettingsDraft draft, std::function<void(Result<Settings>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("save-settings", rivet::Value::List{detail::encode_SettingsDraft(draft)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<Settings> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Settings(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> start_download() { auto raw = backend_.call("start-download", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t start_download_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("start-download", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<UpdateState> update_state() { auto raw = backend_.call("update-state", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> UpdateState { return detail::decode_UpdateState(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_state_async(std::function<void(Result<UpdateState>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update-state", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<UpdateState> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_UpdateState(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

  // Shared state
  std::future<DaemonStatus> get_status() { auto raw = backend_.get_state("status"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DaemonStatus { return detail::decode_DaemonStatus(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_status_async(std::function<void(Result<DaemonStatus>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("status", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<DaemonStatus> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DaemonStatus(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DaemonStatus> set_status(DaemonStatus value) { auto raw = backend_.set_state("status", detail::encode_DaemonStatus(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DaemonStatus { return detail::decode_DaemonStatus(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_status_async(DaemonStatus value, std::function<void(Result<DaemonStatus>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("status", detail::encode_DaemonStatus(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<DaemonStatus> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DaemonStatus(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::linux_runtime::Backend& backend_;
};

}  // namespace rivet_app
